spring:
  application:
    name: flag-quiz
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/flag_quiz"
    username: flagquiz
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
